name: ARCANE×ARMIN

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: print("Lightning has been deployed! ")


          replace: print("ARCANE has been deployed! ")


      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replaced new name'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: arcane120

          commit_user_email: officialarcane120@gmail.com
